services:
  objstorage:
    container_name: objstorage
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    volumes:
      - objdata:/var/lib/minio/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB={POSTGRES_DB}
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      # specifying user and database is needed to avoid `FATAL:  role "root" does not exist`
      # spam in the logs
      test: ['CMD', 'pg_isready', '-U', 'prisma', '-d', 'tests']
      interval: 5s
      timeout: 2s
      retries: 20
  queue:
    container_name: queue
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - queuedata:/var/lib/rabbitmq/data
volumes:
  dbdata:
  objdata:
  queuedata:
